name: wxreader-py37
channels:
  - defaults
variables:
  NO_PROXY: "*"
  no_proxy: "*"
dependencies:
  - python=3.7
  - pip
  - pip:
      - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
      - --trusted-host pypi.tuna.tsinghua.edu.cn
      - PySide6~=6.4.0
      - cefpython3==66.0
      - pyinstaller~=5.5
